BROWSER_NAME = 'firefox'
KINDLE_NOTEBOOK = 'https://read.amazon.com/kp/notebook'
BOOK_STORAGE_FOLDER = 'Book Storage/'
TRUNCATED_HIGHLIGHT_STYLE = 'style="color:red;"'
NEW_HIGHLIGHT_FOLDER = 'New Highlights/'